### PR TITLE
chore: sync recent rwkv.cpp version

### PR DESCRIPTION
**Pull request by yorkzero831**
Sync recent rwkv.cpp version

### Important
Since rwkv.cpp has merge recent version of ggml, which leads format break of old quantized models.

will work on with cuBlas feature soon

### CODE REVIEW

**Comment by yorkzero831** [comment]
fixing the lint problem

**Comment by yorkzero831** [comment]
checking compile error on macos ....

**Comment by hlhr202** [comment]
CUDA is definitely not supported by Apple...

**Comment by yorkzero831** [comment]
> > checking compile error on macos ....
> 
> I think you can use cargo feature flag which serves CUDA as an optional

The feature has not been implemented in this pr yet, gonna to sync the recent version of rwkv.cpp before bring CUDA here

**Comment by yorkzero831** [comment]
I opened a PR to fix this issue on rwkv.cpp 
https://github.com/saharNooby/rwkv.cpp/pull/79

Will keep updating

**Comment by yorkzero831** [comment]
@hlhr202 The compile error of rwkv.cpp has been fixed. ready to be merged

**Pull request merged**
